# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[azure]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[conda]
format = "[$symbol$environment]($style) "
symbol = " "

[hostname]
ssh_only = false
style = "bold blue"
